import numpy as np
import cv2
from typing import Dict, List, Tuple, Optional

class HomographyMapper:
    """
    Handles translation of camera pixel coordinates (x, y) to 
    physical 2D store floor plan coordinates (X, Y) using a homography matrix.
    """
    def __init__(self, camera_id: str):
        self.camera_id = camera_id
        self.H = None
        self._load_calibration()
        
    def _load_calibration(self):
        """
        Loads the calibration points for the camera.
        For Brigade Road Store (ST1008), reference points are marked on the floor plan.
        We define 4 matching screen (src) and floor plan (dst) coordinates.
        """
        # Example calibration points for mapping:
        # src: 4 points on the camera image plane
        # dst: 4 corresponding points on the floor plan image plane
        if self.camera_id == "CAM_ENTRY_01":
            src = np.array([[100, 450], [500, 450], [550, 700], [50, 700]], dtype=np.float32)
            dst = np.array([[200, 100], [800, 100], [800, 700], [200, 700]], dtype=np.float32)
            self.H = cv2.getPerspectiveTransform(src, dst)
        elif self.camera_id == "CAM_FLOOR_01":
            src = np.array([[120, 300], [600, 300], [640, 680], [80, 680]], dtype=np.float32)
            dst = np.array([[100, 100], [900, 100], [900, 800], [100, 800]], dtype=np.float32)
            self.H = cv2.getPerspectiveTransform(src, dst)
        else:
            # Default identity matrix if uncalibrated
            self.H = np.eye(3, dtype=np.float32)

    def map_to_floor(self, bbox: Tuple[int, int, int, int]) -> Tuple[float, float]:
        """
        Maps a person's bounding box to 2D floor coordinates.
        Uses the bottom-center of the bounding box as the feet position.
        """
        x1, y1, x2, y2 = bbox
        feet_x = (x1 + x2) / 2.0
        feet_y = y2  # Bottom edge of the box
        
        # Apply homography projection
        point = np.array([[[feet_x, feet_y]]], dtype=np.float32)
        projected = cv2.perspectiveTransform(point, self.H)
        
        X = float(projected[0][0][0])
        Y = float(projected[0][0][1])
        return X, Y

class ReIDManager:
    """
    Manages matching visitor identities across different cameras
    using feature embeddings generated by a Re-ID model (e.g., OSNet).
    """
    def __init__(self, similarity_threshold: float = 0.75):
        self.similarity_threshold = similarity_threshold
        # Stores global active sessions: visitor_id -> list of embeddings
        self.gallery: Dict[str, List[np.ndarray]] = {}
        
    def extract_embedding(self, frame: np.ndarray, bbox: Tuple[int, int, int, int]) -> np.ndarray:
        """
        Crops the bounding box from the frame and runs it through the OSNet feature extractor.
        Returns a normalized 512-dimensional embedding vector.
        """
        x1, y1, x2, y2 = map(int, bbox)
        crop = frame[max(0, y1):y2, max(0, x1):x2]
        
        if crop.size == 0:
            return np.zeros(512, dtype=np.float32)
            
        # Placeholder for actual model inference (e.g., torchreid / ONNX Runtime)
        # Returns a unit-length normalized random vector for structure
        emb = np.random.randn(512).astype(np.float32)
        emb /= np.linalg.norm(emb)
        return emb

    def match_visitor(self, embedding: np.ndarray) -> Optional[str]:
        """
        Compares the target embedding with all active visitor embeddings in the gallery.
        Returns the visitor_id if matched, else None.
        """
        best_match_id = None
        best_score = -1.0
        
        for visitor_id, embeddings in self.gallery.items():
            for gallery_emb in embeddings:
                # Cosine similarity since both vectors are normalized
                similarity = float(np.dot(embedding, gallery_emb))
                if similarity > best_score:
                    best_score = similarity
                    best_match_id = visitor_id
                    
        if best_score >= self.similarity_threshold:
            # Append new embedding to gallery to account for pose/lighting changes
            self.gallery[best_match_id].append(embedding)
            # Limit history to prevent drift
            if len(self.gallery[best_match_id]) > 5:
                self.gallery[best_match_id].pop(0)
            return best_match_id
            
        return None

    def register_new_visitor(self, visitor_id: str, embedding: np.ndarray):
        """Registers a new visitor session in the Re-ID database."""
        self.gallery[visitor_id] = [embedding]
